# -*- coding: utf-8 -*-
"""w5d2-eda-mes-notes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QUmkfiwQj-16X9KsiSsTbyj-PROPBVl
"""

import requests
import os

def download_github_folder(api_url, local_dir):
  response = requests.get(api_url)
  if response.status_code != 200:
    print(f"Error: Could not fetch the content from {api_url}")
    return # Added return statement here

  items = response.json()

  if not os.path.exists(local_dir):
    os.makedirs(local_dir)
    print(f'Created the directory: {local_dir}')

  for item in items:
    if item['type'] == 'file':
      file_url = item['download_url']
      file_path = os.path.join(local_dir, item['name'])

      print(f'Downloading file: {item['name']}')
      file_data = requests.get(file_url).content
      with open(file_path, 'wb') as f:
        f.write(file_data)

    elif item['type'] == 'dir':
      new_api_url = item['url']
      new_local_dir = os.path.join(local_dir, item['name'])
      print(f'Entering the folder: {item['name']}')
      download_github_folder(new_api_url, new_local_dir)

repo_owner = "hereandnowai"
repo_name = "ml-data-hereandnowai"
folder_path = "data-for-eda"

api_base_url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/content/{folder_path}"
print("Starting to download from HERE AND NOW AI's repo")
download_github_folder(api_base_url, "data")
print("All the datasets are successfully downloaded")

"""### download the datasets"""

import requests
import os

def download_github_folder(api_url, local_dir):
    """
    Recursively downloads files and folders from a GitHub repository using the REST API.
    """
    response = requests.get(api_url)

    if response.status_code != 200:
        print(f"Error: Could not fetch content from {api_url}")
        return

    items = response.json()

    # Ensure the local directory exists
    if not os.path.exists(local_dir):
        os.makedirs(local_dir)
        print(f"Created directory: {local_dir}")

    for item in items:
        if item['type'] == 'file':
            # Download individual files
            file_url = item['download_url']
            file_path = os.path.join(local_dir, item['name'])

            print(f"Downloading file: {item['name']}...")
            file_data = requests.get(file_url).content
            with open(file_path, 'wb') as f:
                f.write(file_data)

        elif item['type'] == 'dir':
            # Create sub-directory and go deeper (Recursion)
            new_api_url = item['url']
            new_local_dir = os.path.join(local_dir, item['name'])
            print(f"Entering folder: {item['name']}...")
            download_github_folder(new_api_url, new_local_dir)

# --- CONFIGURATION ---
# Target: https://github.com/hereandnowai/ml-data-hereandnowai/tree/main/data-for-eda
repo_owner = "hereandnowai"
repo_name = "ml-data-hereandnowai"
folder_path = "data-for-eda"

# GitHub API URL format: https://api.github.com/repos/{owner}/{repo}/contents/{path}
api_base_url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/contents/{folder_path}"

# Start the download process into a local folder named 'data'
print("Starting bulk download from HERE AND NOW AI GitHub...")
download_github_folder(api_base_url, "data")
print("\nAll files and folders downloaded successfully!")

"""### loading the dataset"""

import numpy as np
import pandas as pd

covid_data = pd.read_csv("/content/data/1-statistics/covid-data.csv")

covid_data.head(5)

covid_data = covid_data[['iso_code','continent','location','date','total_cases','new_cases']]

covid_data.head(5)

covid_data.dtypes

covid_data.shape

"""## part 1 | statistics

### eda-mean
"""

# mean using numpy
data_mean = np.mean(covid_data["new_cases"])
data_mean

# mean using pandas
data_mean = covid_data["new_cases"].mean()
data_mean



"""### eda-median"""

# medain using numpy
data_median = np.median(covid_data["new_cases"])
data_median

# median using pandas
data_median = covid_data["new_cases"].median()
data_median

"""### eda-mode"""

import numpy as np
import pandas as pd
from scipy import stats

data_mode = stats.mode(covid_data["new_cases"])
data_mode

data_mode[0]

data_mode = covid_data["continent"].mode()
data_mode

covid_data['continent'].value_counts()



"""### variance"""

# Variance measures how far each value is from the average
# variance using numpy
data_variance = np.var(covid_data["new_cases"])
data_variance

# variance using pandas
covid_data["new_cases"].var()

"""### sd"""

data_sd = np.std(covid_data["new_cases"])
data_sd

covid_data["new_cases"].std()

"""### range"""

data_max = np.max(covid_data["new_cases"])
data_min = np.min(covid_data["new_cases"])

print(data_max,data_min)

data_range = data_max - data_min
data_range

data_max = covid_data["new_cases"].max()
data_min = covid_data["new_cases"].min()

data_range = data_max - data_min
data_range

"""### percentile"""

data_percentile = np.percentile(covid_data["new_cases"], 60)
data_percentile

"""### quartile"""

data_quartile = np.quantile(covid_data["new_cases"],0.75)
data_quartile

"""### interquartile"""

data_IQR = stats.iqr(covid_data["new_cases"], interpolation = 'midpoint')
data_IQR

data_IQR = stats.iqr(covid_data["new_cases"])
data_IQR

"""## part 2 | preparing for eda-1

### grouping data
"""

# grouping data
marketing_data = pd.read_csv("/content/data/2-preparing-for-eda/marketing_campaign.csv")

marketing_data.head()

marketing_data = marketing_data[['ID', 'Year_Birth', 'Education', 'Marital_Status',
                'Income', 'Kidhome', 'Teenhome', 'Dt_Customer',
                'Recency','NumStorePurchases', 'NumWebVisitsMonth']]

marketing_data.head(2).T

marketing_data.dtypes

marketing_data.shape

# Check the average number of store purchases of customers based on number of kids in the home
marketing_data.groupby('Kidhome')['NumStorePurchases'].mean()



"""### appending data"""



"""## part 3 | preparing for eda-2"""

import pandas as pd

houseprices_data = pd.read_csv("/content/data/3-visualizing-data-in-python/HousingPricesData.csv")

houseprices_data = houseprices_data[['Zip', 'Price', 'Area', 'Room']]

houseprices_data.head()

houseprices_data.shape

houseprices_data.dtypes

houseprices_data['PriceperSqm'] = houseprices_data['Price']/houseprices_data['Area']

houseprices_data.head()

# Visualizing data in Matplotlib.ipynb

import pandas as pd
import matplotlib.pyplot as plt

houseprices_data = pd.read_csv("/content/data/3-visualizing-data-in-python/HousingPricesData.csv")

houseprices_sorted = houseprices_data.sort_values('Price', ascending = False)

plt.figure(figsize= (12,6))

x = houseprices_sorted['Zip'][0:10]
y = houseprices_sorted['Price'][0:10]
plt.bar(x,y)
plt.show()

plt.figure(figsize= (12,6))
plt.bar(x,y)
plt.title('Top 10 Areas with the highest house prices', fontsize=15)
plt.xlabel('Zip code', fontsize = 12)
plt.xticks(fontsize=10)
plt.ylabel('House prices in millions', fontsize=12)
plt.yticks(fontsize=10)
plt.show()

fig, ax = plt.subplots(figsize=(40,18))

# Ensure PriceperSqm is available in houseprices_sorted
houseprices_sorted['PriceperSqm'] = houseprices_sorted['Price'] / houseprices_sorted['Area']

x = houseprices_sorted['Zip'][0:10]
y = houseprices_sorted['Price'][0:10]
y1 = houseprices_sorted['PriceperSqm'][0:10]

plt.subplot(1,2,1)
plt.bar(x,y)
plt.xticks(fontsize=17)
plt.ylabel('House prices in millions', fontsize=25)
plt.yticks(fontsize=20)
plt.title('Top 10 Areas with the highest house prices', fontsize=25)

plt.subplot(1,2,2)
plt.bar(x,y1)
plt.xticks(fontsize=17)
plt.ylabel('House prices per sqm', fontsize=25)
plt.yticks(fontsize=20)
plt.title('Top 10 Areas with the highest house prices per sqm', fontsize=25)
plt.show()

"""### seaborn"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

houseprices_data['PriceperSqm'] = houseprices_data['Price']/houseprices_data['Area']

houseprices_sorted = houseprices_data.sort_values('Price', ascending = False)

houseprices_sorted.head()

plt.figure(figsize= (12,6))
data = houseprices_sorted[0:10]
# sns.barplot(data=data, x='Zip', y='Price', palette='viridis')
# sns.barplot(data=data, x='Zip', y='Price', palette='Set2')
sns.barplot(data=data, x='Zip', y='Price', palette='deep')

plt.figure(figsize= (12,6))
data = houseprices_sorted[0:10]

ax = sns.barplot(data= data, x= 'Zip',y = 'Price', palette='deep')
ax.set_xlabel('Zip code',fontsize = 15)
ax.set_ylabel('House prices in millions', fontsize = 15)
ax.set_title('Top 10 Areas with the highest house prices', fontsize= 20)

fig, ax = plt.subplots(1, 2,figsize=(40,18))

data = houseprices_sorted[0:10]

sns.set(font_scale = 3)
ax1 = sns.barplot(data= data, x= 'Zip',y = 'Price', ax = ax[0], palette='deep')
ax1.set_xlabel('Zip code')
ax1.set_ylabel('House prices in millions')
ax1.set_title('Top 10 Areas with the highest house prices')


ax2 = sns.barplot(data= data, x= 'Zip',y = 'PriceperSqm', ax=ax[1], palette='deep')
ax2.set_xlabel('Zip code')
ax2.set_ylabel('House prices per sqm')
ax2.set_title('Top 10 Areas with the highest price per sqm')

"""### ggplot"""

import pandas as pd
from plotnine import *

chart_data = houseprices_sorted[0:10]

ggplot(chart_data,aes(x='Zip',y = 'Price')) + geom_bar(stat = 'identity') \
+ scale_x_discrete(limits=chart_data['Zip'].tolist()) + theme(figure_size=(16, 8))

ggplot(chart_data,aes(x='Zip',y = 'Price')) + geom_bar(stat = 'identity') \
+ scale_x_discrete(limits=chart_data['Zip'].tolist()) \
+ labs(y='House prices in millions', x='Zip code', title='Top 10 Areas with the highest house prices') \
+ theme(figure_size=(16, 8),
        axis_title=element_text(face='bold',size =12),
          axis_text=element_text(face='italic',size =8),
          plot_title=element_text(face='bold',
                                  size=12))

"""### bokeh"""

import pandas as pd
from bokeh.plotting import figure, show
import bokeh.plotting as bk_plot
from bokeh.io import output_notebook
output_notebook()

data = houseprices_sorted[0:10]

fig = figure(x_range = data['Zip'], width = 700, height = 500)
fig.vbar(x= data['Zip'], top = data['Price'], width = 0.9)
show(fig)

fig = figure(x_range = data['Zip'], width = 700, height = 500,
             title = 'Top 10 Areas with the highest house prices', x_axis_label = 'Zip code',
             y_axis_label = 'House prices in millions')

fig.vbar(x= data['Zip'], top = data['Price'], width = 0.9)


fig.xaxis.axis_label_text_font_size = "15pt"
fig.xaxis.major_label_text_font_size = "10pt"
fig.yaxis.axis_label_text_font_size = "15pt"
fig.yaxis.major_label_text_font_size = "10pt"
fig.title.text_font_size = '15pt'


show(fig)

p1 = figure(x_range = data['Zip'], width = 480, height = 400,
             title = 'Top 10 Areas with the highest house prices', x_axis_label = 'Zip code',
             y_axis_label = 'House prices in millions')

p1.vbar(x= data['Zip'], top = data['Price'], width = 0.9)

p2 = figure(x_range = data['Zip'], width = 480, height = 400,
             title = 'Top 10 Areas with the highest house prices per sqm', x_axis_label = 'Zip code',
             y_axis_label = 'House prices per sqm')

p2.vbar(x= data['Zip'], top = data['PriceperSqm'], width = 0.9)


gp = bk_plot.gridplot(children=[[p1, p2]])
bk_plot.show(gp)

"""## univariate analysis"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

penguins_data = pd.read_csv("/content/data/4-performing-univariate-analysis-in-python/penguins_size.csv")

penguins_data = penguins_data[['species','culmen_length_mm']]

penguins_data.head()

penguins_data.shape

penguins_data.dtypes

sns.histplot( data = penguins_data, x= penguins_data["culmen_length_mm"])

plt.figure(figsize= (12,6))

ax = sns.histplot( data = penguins_data, x= penguins_data["culmen_length_mm"])
ax.set_xlabel('Culmen Length in mm',fontsize = 15)
ax.set_ylabel('Count of records', fontsize = 15)
ax.set_title('Univariate analysis of Culmen Length', fontsize= 20)

"""### boxplot"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

houseprices_data = pd.read_csv("/content/data/4-performing-univariate-analysis-in-python/HousingPricesData.csv")

houseprices_data = houseprices_data[['Zip','Price','Area','Room']]

houseprices_data.head()

houseprices_data.shape

houseprices_data.dtypes

sns.boxplot(data = houseprices_data, x= houseprices_data["Price"])

plt.figure(figsize= (12,6))

ax = sns.boxplot(data = houseprices_data, x= houseprices_data["Price"])
ax.set_xlabel('House Prices in millions',fontsize = 15)
ax.set_title('Univariate analysis of House Prices', fontsize= 20)
plt.ticklabel_format(style='plain', axis='x')

"""### violinplot"""

sns.violinplot(data = houseprices_data, x= houseprices_data["Price"])

plt.figure(figsize= (12,6))

ax = sns.violinplot(data = houseprices_data, x= houseprices_data["Price"])
ax.set_xlabel('House Prices in millions',fontsize = 15)
ax.set_title('Univariate analysis of House Prices', fontsize= 20)
plt.ticklabel_format(style='plain', axis='x')

"""### summary table"""

houseprices_data.describe()

sns.countplot(data = penguins_data, x= penguins_data['species'], palette='deep')

plt.figure(figsize= (12,6))

ax = sns.countplot(data = penguins_data, x= penguins_data['species'], palette='deep')
ax.set_xlabel('Penguin Species',fontsize = 15)
ax.set_ylabel('Count of records',fontsize = 15)
ax.set_title('Univariate analysis of Penguin Species', fontsize= 20)

penguins_group = penguins_data.groupby('species').count()
penguins_group

penguins_group= penguins_group.reset_index()
penguins_group

#create pie chart
plt.pie(penguins_group["culmen_length_mm"], labels = penguins_group['species'])
plt.show()

cols = ['g', 'b', 'r']

plt.pie(penguins_group["culmen_length_mm"], labels = penguins_group['species'],colors = cols)

plt.title('Univariate Analysis of Species', fontsize=15)
plt.show()

penguins_data = pd.read_csv("/content/data/5-performing-bivariate-analysis-in-python/penguins_size.csv")

sns.scatterplot(data = penguins_data, x= penguins_data["culmen_length_mm"], y= penguins_data['body_mass_g'])

plt.figure(figsize= (12,6))

ax = sns.scatterplot(data = penguins_data, x= penguins_data["culmen_length_mm"], y= penguins_data['body_mass_g'])
ax.set_title('Bivariate analysis of Culmen Length and body mass', fontsize= 20)

# Create a Crosstab in Pandas
pd.crosstab(index= penguins_data['species'], columns= penguins_data['sex'])

# Create a Pivot Table in Pandas
pd.pivot_table(penguins_data, values='culmen_length_mm',
                                index='species',
                                aggfunc=np.mean)

# 2 categorical variables and 1 numerical variable

pd.pivot_table(penguins_data, values='culmen_length_mm',
                                index='species',
                                columns='sex',
                                aggfunc=np.mean)

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="ticks", font_scale=0.8)

g = sns.pairplot(
    penguins_data,
    height=3
)

g.fig.tight_layout()

# two variables bar chart

sns.barplot(
    data=penguins_data,
    x=penguins_data['species'],
    y=penguins_data['culmen_length_mm'],
    estimator=np.median,
    palette='deep'
)

plt.figure(figsize= (12,6))

ax = sns.barplot(data = penguins_data,
                 x=penguins_data['species'],
                 y=penguins_data['culmen_length_mm'],
                 estimator = np.median,
                 palette='deep')

ax.set_xlabel('Species',fontsize = 15)
ax.set_ylabel('Culmen_length_mm', fontsize = 15)
ax.set_title('Bivariate analysis of Culmen Length and Species', fontsize= 20)

sns.boxplot( data = penguins_data,
                    x= penguins_data['species'],
                    y= penguins_data["culmen_length_mm"],
                    palette='deep')

plt.figure(figsize= (12,6))

ax = sns.boxplot(data = penguins_data,
                 x= penguins_data['species'],
                 y= penguins_data["culmen_length_mm"],
                 palette='deep')

ax.set_xlabel('Species',fontsize = 15)
ax.set_ylabel('Culment Length in mm', fontsize = 15)
ax.set_title('Bivariate analysis of Culmen Length and Species', fontsize= 20)

penguins_data_male = penguins_data.loc[penguins_data['sex']== 'MALE',:]
penguins_data_female = penguins_data.loc[penguins_data['sex']== 'FEMALE',:]

sns.histplot(data = penguins_data_male,
                    x= penguins_data_male["culmen_length_mm"],
                    alpha=0.5,
                    color = 'blue')

sns.histplot(data = penguins_data_female,
                    x= penguins_data_female["culmen_length_mm"],
                    alpha=0.5,
                    color = 'red')

plt.figure(figsize= (12,6))

ax = sns.histplot(data = penguins_data_male,
                         x= penguins_data_male["culmen_length_mm"],
                         alpha=0.5,
                         color = 'blue')

ax = sns.histplot(data = penguins_data_female,
                         x= penguins_data_female["culmen_length_mm"],
                         alpha=0.5,
                         color = 'red')

ax.set_xlabel('Culmen Length in mm',fontsize = 15)
ax.set_ylabel('Count of records', fontsize = 15)
ax.set_title('Bivariate analysis of Culmen Length and Sex', fontsize= 20)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

penguins_data = pd.read_csv("/content/data/5-performing-bivariate-analysis-in-python/penguins_size.csv")
penguins_data = penguins_data[['species','culmen_length_mm', 'body_mass_g']]
penguins_corr = penguins_data.corr(numeric_only=True)
heatmap = sns.heatmap(penguins_corr, vmin=-1, vmax=1, annot=True)

plt.figure(figsize=(16, 6))

heatmap = sns.heatmap(penguins_data.corr(numeric_only=True), vmin=-1, vmax=1, annot=True)

heatmap.set_title('Correlation Heatmap', fontdict={'fontsize':24}, pad=12);

# Multivariate analysis

# Implementing Cluster Analysis on multiple variables using Kmeans

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

marketing_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/marketing_campaign.csv")

marketing_data = marketing_data[['MntWines','MntFruits', 'MntMeatProducts', 'MntFishProducts',
                                 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
                                 'NumWebPurchases','NumCatalogPurchases', 'NumStorePurchases',
                                 'NumWebVisitsMonth']]

marketing_data.head()

marketing_data.shape

marketing_data.dtypes

marketing_data.isnull().sum()

marketing_data.dropna(inplace=True)

marketing_data.shape

"""# Scale the data"""

scaler = StandardScaler()
marketing_data_scaled = scaler.fit_transform(marketing_data)

kmeans = KMeans(n_clusters= 4, init='k-means++',random_state= 1)

kmeans.fit(marketing_data_scaled)

label = kmeans.fit_predict(marketing_data_scaled)
marketing_data_test = marketing_data.copy()
marketing_data_test['label'] = label
marketing_data_test['label'] = marketing_data_test['label'].astype(str)

plt.figure(figsize= (18,10))
sns.scatterplot(x= marketing_data_test['MntWines'],
                y= marketing_data_test['MntFruits'],
                hue = marketing_data_test['label'])

# Choosing the Optimal number of K clusters in Kmeans.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

marketing_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/marketing_campaign.csv")

marketing_data = marketing_data[['MntWines','MntFruits', 'MntMeatProducts', 'MntFishProducts',
                                 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
                                 'NumWebPurchases','NumCatalogPurchases', 'NumStorePurchases',
                                 'NumWebVisitsMonth']]

marketing_data.head()

kmeans = KMeans(n_clusters= 4, init='k-means++',random_state = 1)
kmeans.fit(marketing_data_scaled)

label = kmeans.fit_predict(marketing_data_scaled)

marketing_data_output = marketing_data.copy()
marketing_data_output['cluster'] = label
marketing_data_output['cluster'].value_counts()

distance_values = []
for cluster in range(1,14):
    kmeans = KMeans(n_clusters = cluster, init='k-means++')
    kmeans.fit(marketing_data_scaled)
    distance_values.append(kmeans.inertia_)

cluster_output = pd.DataFrame({'Cluster':range(1,14), 'distance_values':distance_values})
plt.figure(figsize=(12,6))
plt.plot(cluster_output['Cluster'], cluster_output['distance_values'], marker='o')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')

# Profiling Kmeans Clusters.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

marketing_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/marketing_campaign.csv")

marketing_data = marketing_data[['MntWines','MntFruits', 'MntMeatProducts', 'MntFishProducts',
                                 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
                                 'NumWebPurchases','NumCatalogPurchases', 'NumStorePurchases',
                                 'NumWebVisitsMonth']]

marketing_data.head()

marketing_data.shape

scaler = StandardScaler()
marketing_data_scaled = scaler.fit_transform(marketing_data)

kmeans = KMeans(n_clusters= 4, init='k-means++',random_state = 1)

kmeans.fit(marketing_data_scaled)

label = kmeans.fit_predict(marketing_data_scaled)
marketing_data_output = marketing_data.copy()
marketing_data_output['cluster'] = label
marketing_data_output['cluster'].value_counts()

# Profiling Clusters

cols  =['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts',
       'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
       'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases',
       'NumWebVisitsMonth']

overall_mean = marketing_data_output[cols].apply(np.mean).T
overall_mean = pd.DataFrame(overall_mean,columns =['overall_average'])
overall_mean

cluster_mean = marketing_data_output.groupby('cluster')[cols].mean().T
cluster_mean

pd.concat([cluster_mean,overall_mean],axis =1)

# Implementing Principal Component Analysis (PCA) on multiple variables.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

marketing_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/marketing_campaign.csv")

marketing_data = marketing_data[['MntWines','MntFruits', 'MntMeatProducts', 'MntFishProducts',
                                 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
                                 'NumWebPurchases','NumCatalogPurchases', 'NumStorePurchases',
                                 'NumWebVisitsMonth']]

marketing_data.head()

marketing_data.shape

marketing_data.dtypes

marketing_data.isnull().sum()

marketing_data.dropna(inplace=True)

marketing_data.shape

# Scale the data
x = marketing_data.values
marketing_data_scaled = StandardScaler().fit_transform(x)

# Apply PCA to the dataset
pca_marketing = PCA(n_components=6,random_state = 1)
principalComponents_marketing = pca_marketing.fit_transform(marketing_data_scaled)

principal_marketing_data = pd.DataFrame(data = principalComponents_marketing
             , columns = ['principal component 1', 'principal component 2',
                          'principal component 3','principal component 4'
                         ,'principal component 5','principal component 6'])
principal_marketing_data

# Ch6/5. Choosing the number of Principal Components

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

marketing_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/marketing_campaign.csv")

marketing_data = marketing_data[['MntWines','MntFruits', 'MntMeatProducts', 'MntFishProducts',
                                 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
                                 'NumWebPurchases','NumCatalogPurchases', 'NumStorePurchases',
                                 'NumWebVisitsMonth']]

# Scale the data
x = marketing_data.values
marketing_data_scaled = StandardScaler().fit_transform(x)

# Apply PCA to the dataset
pca_marketing = PCA(n_components=6, random_state=1)
principalComponents_marketing = pca_marketing.fit_transform(marketing_data_scaled)

principal_marketing_data = pd.DataFrame(data = principalComponents_marketing
             , columns = ['principal component 1', 'principal component 2',
                          'principal component 3','principal component 4'
                         ,'principal component 5','principal component 6'])

# Check the explained variance
for i in range(0,len(pca_marketing.explained_variance_ratio_)):
    print("Component ",i ," ",pca_marketing.explained_variance_ratio_[i])

# Create a Scree Plot

plt.figure(figsize= (12,6))

PC_values = np.arange(pca_marketing.n_components_) + 1
cummulative_variance = np.cumsum(pca_marketing.explained_variance_ratio_)
plt.plot(PC_values, cummulative_variance, 'o-', linewidth=2, color='blue')
plt.title('Scree Plot')
plt.xlabel('Principal Components')
plt.ylabel('Cummulative Explained Variance')
plt.show()

# Ch6/6. Analysing Principal Components.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

marketing_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/marketing_campaign.csv")

marketing_data = marketing_data[['MntWines','MntFruits', 'MntMeatProducts', 'MntFishProducts',
                                 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
                                 'NumWebPurchases','NumCatalogPurchases', 'NumStorePurchases',
                                 'NumWebVisitsMonth']]

# Scale the data
x = marketing_data.values
marketing_data_scaled = StandardScaler().fit_transform(x)

# Apply PCA to the dataset
pca_marketing = PCA(n_components=6, random_state = 1)
principalComponents_marketing = pca_marketing.fit_transform(marketing_data_scaled)

principal_marketing_data = pd.DataFrame(data = principalComponents_marketing
             , columns = ['principal component 1', 'principal component 2',
                          'principal component 3','principal component 4'
                         ,'principal component 5','principal component 6'])

# Check the loadings
loadings_df = pd.DataFrame(pca_marketing.components_).T
loadings_df = loadings_df.set_index(marketing_data.columns)
loadings_df

loadings_df.where(abs(loadings_df) >= 0.35)

# Ch6/7. Implementing Factor Analysis on multiple variables.ipynb

!pip install factor_analyzer

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_kmo

satisfaction_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/website_survey.csv")

satisfaction_data = satisfaction_data[['q1', 'q2', 'q3','q4', 'q5', 'q6', 'q7', 'q8', 'q9',
                                       'q10', 'q11', 'q12', 'q13', 'q14','q15', 'q16', 'q17',
                                       'q18', 'q19', 'q20', 'q21', 'q22', 'q23', 'q24','q25', 'q26']]

# Inspect first 5 rows and data types of the dataset
satisfaction_data.head()

satisfaction_data.shape
satisfaction_data.dtypes
satisfaction_data.isnull().sum()
satisfaction_data.dropna(inplace=True)
satisfaction_data.shape

# Check for multicollinearity

satisfaction_data.corr()

satisfaction_data.corr()[(satisfaction_data.corr()>0.9) & (satisfaction_data.corr()<1)]

# Test the suitability of the dataset

kmo_all,kmo_model=calculate_kmo(satisfaction_data)
kmo_model

# Apply Factor Analysis to dataset
fa = FactorAnalyzer(n_factors = 6, rotation="varimax")
fa.fit(satisfaction_data)

loadings_output = pd.DataFrame(fa.loadings_,index=satisfaction_data.columns)
loadings_output

# Ch6/8. Determining the number of factors.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_kmo

satisfaction_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/website_survey.csv")

satisfaction_data = satisfaction_data[['q1', 'q2', 'q3','q4', 'q5', 'q6', 'q7', 'q8',
                                       'q9', 'q10', 'q11', 'q12', 'q13', 'q14','q15', 'q16', 'q17',
                                       'q18', 'q19', 'q20', 'q21', 'q22', 'q23', 'q24','q25', 'q26']]

satisfaction_data.corr()

satisfaction_data.corr()[(satisfaction_data.corr()>0.8) & (satisfaction_data.corr()<1)]

# Apply Factor Analysis to dataset
fa = FactorAnalyzer(n_factors = 6, rotation="varimax")
fa.fit(satisfaction_data)

# Get variance of each factors
pd.DataFrame(fa.get_factor_variance(),index=['Variance','Proportional Var','Cumulative Var'])

# Create Scree plot
fa = FactorAnalyzer(rotation = 'varimax',n_factors=satisfaction_data.shape[1])
fa.fit(satisfaction_data)
ev,_ = fa.get_eigenvalues()

factor_values = np.arange(satisfaction_data.shape[1]) + 1

plt.figure(figsize= (12,6))

plt.plot(factor_values,ev,'o-', linewidth=2)
plt.title('Scree Plot')
plt.xlabel('Factors')
plt.ylabel('Eigen Value')
plt.grid()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_kmo

satisfaction_data = pd.read_csv("/content/data/6-performing-multivariate-analysis-in-python/website_survey.csv")

satisfaction_data = satisfaction_data[['q1', 'q2', 'q3','q4', 'q5', 'q6', 'q7', 'q8', 'q9',
                                       'q10', 'q11', 'q12', 'q13', 'q14','q15', 'q16', 'q17',
                                       'q18', 'q19', 'q20', 'q21', 'q22', 'q23', 'q24','q25', 'q26']]

# Check for multicollinearity
satisfaction_data.corr()

satisfaction_data.corr()[(satisfaction_data.corr()>0.9) & (satisfaction_data.corr()<1)]

# Apply Factor Analysis to dataset
fa = FactorAnalyzer(n_factors = 5, rotation="varimax")
fa.fit(satisfaction_data)

# Analyse the factors
loadings_output = pd.DataFrame(fa.loadings_,index=satisfaction_data.columns)
loadings_output

loadings_output.where(abs(loadings_output) > 0.5)

pd.DataFrame(fa.get_communalities(),index=satisfaction_data.columns,columns=['Communalities'])

# Ch7/1. Using line and boxplots to visualise time series data.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

air_traffic_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/SF_Air_Traffic_Passenger_Statistics_Transformed.csv")

air_traffic_data.head()

air_traffic_data.shape

air_traffic_data.dtypes

# Transform date int to date
air_traffic_data['Date']= pd.to_datetime(air_traffic_data['Date'], format = "%Y%m")

air_traffic_data.dtypes

# Set date as index
air_traffic_data.set_index('Date',inplace = True)
air_traffic_data.shape

# Plot time series using line plot
plt.figure(figsize= (18,10))

plt.plot(air_traffic_data.index, air_traffic_data['Total Passenger Count'], color='tab:red')
plt.title("Time series analysis of San Franscisco Air Traffic",fontsize = 20)
plt.ticklabel_format(style='plain', axis='y')

# Plot time series using boxplot
plt.figure(figsize= (18,10))

data_subset = air_traffic_data[air_traffic_data.index < '2010-01-01']

ax = sns.boxplot(data = data_subset , x= pd.PeriodIndex(data_subset.index, freq='Q'),
                 y= data_subset['Total Passenger Count'], palette='deep')

ax.set_title("Time series analysis of San Franscisco Air Traffic",fontsize = 20)

plt.ticklabel_format(style='plain', axis='y')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

air_traffic_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/SF_Air_Traffic_Passenger_Statistics_Transformed.csv")

def quick_eda(df, name="Dataset"):
    print(f"\n📊 {name} - Quick EDA Report")
    print("-" * 50)

    print("\n1. First 5 Rows:")
    display(df.head())

    print("\n2. Shape:")
    print(df.shape)

    print("\n3. Data Types:")
    print(df.dtypes)

    print("\n4. Missing Values:")
    print(df.isnull().sum())

    print("\n5. Numerical Summary:")
    display(df.describe())

    print("\n6. Categorical Summary:")

    cat_cols = df.select_dtypes(include='object')

    if cat_cols.shape[1] > 0:
        display(cat_cols.describe())
    else:
        print("No categorical columns found.")

quick_eda(air_traffic_data, name="Air Traffic Data")



weather_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/DailyDelhiClimate.csv")
weather_data.set_index('date', inplace=True)
weather_data.head()

air_traffic_data.dtypes

air_traffic_data.set_index('Date',inplace = True)
air_traffic_data.shape

plt.figure(figsize= (18,10))

plt.plot(air_traffic_data.index, air_traffic_data['Total Passenger Count'], color='tab:red')
plt.title("Time series analysis of San Franscisco Air Traffic",fontsize = 20)
plt.ticklabel_format(style='plain', axis='y')

plt.figure(figsize= (18,10))

data_subset = air_traffic_data[air_traffic_data.index < '2010-01-01']

ax = sns.boxplot(data = data_subset,
                 x= pd.PeriodIndex(data_subset.index,
                  freq='Q'), #air_traffic_data['Date'].dt.month,
                 y= data_subset['Total Passenger Count'],
                 palette='deep')

ax.set_title("Time series analysis of San Franscisco Air Traffic",fontsize = 20)

plt.ticklabel_format(style='plain', axis='y')

from statsmodels.tsa.seasonal import seasonal_decompose

weather_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/DailyDelhiClimate.csv")

air_traffic_data.head(2)

weather_data.head(2)

quick_eda(weather_data, name="Weather Data")

# Transform date column to date data type
# air_traffic_data['Date']= pd.to_datetime(air_traffic_data['Date'], format = "%Y%m")
weather_data['date']= pd.to_datetime(weather_data['date'], format = "%d/%m/%Y")

air_traffic_data.dtypes

weather_data.dtypes

# Plot time series using line plot
plt.figure(figsize= (15,8))

plt.plot(air_traffic_data.index, air_traffic_data['Total Passenger Count'], color='tab:red')
plt.title("Time series analysis of San Franscisco Air Traffic",fontsize = 17)
plt.ticklabel_format(style='plain', axis='y')

plt.figure(figsize= (15,8))

plt.plot(weather_data.index, weather_data['meantemp'], color='tab:blue')
plt.title("Time series analysis of Mean Temperature in Delhi",fontsize = 17)
plt.ticklabel_format(style='plain', axis='y')

# Decompose Timeseries using Multiplicative model
decomposition_multi = seasonal_decompose(air_traffic_data,
                                              model='multiplicative', period = 12)

fig = decomposition_multi.plot()
fig.set_size_inches((10, 9))
plt.show()

# Decompose Timeseries using Additive model
decomposition_add = seasonal_decompose(weather_data,
                                              model='additive',period = 365)

fig = decomposition_add.plot()
fig.set_size_inches((10, 9))
plt.show()

# Ch7/4 Performing Smoothing - Moving Average.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

stock_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/MTNOY.csv")
stock_data = stock_data[['Date','Close']]

stock_data.head()

quick_eda(stock_data, "/content/data/7-analysis-time-series-in-python/MTNOY.csv")

# Transform date int to date
stock_data['Date']= pd.to_datetime(stock_data['Date'], format = "%Y-%m-%d")

stock_data.dtypes

# Set date as index
stock_data.set_index('Date',inplace = True)
stock_data.shape

# Plot the stock data on a line plot
plt.figure(figsize= (18,10))

plt.plot(stock_data.index, stock_data['Close'],color='tab:blue')
plt.title("Time series analysis of MTN Group Limited Stocks",fontsize = 17)

# Perform Moving Average Smoothing
moving_data = stock_data.rolling(window=4)
moving_average_data = moving_data.mean()
moving_average_data.head()

moving_average_data.head()

# Plot moving average against original time series using line plot
plt.figure(figsize= (18,10))

stock_data_subset = stock_data[stock_data.index>= '2015-01-01']
moving_average_data_subset = moving_average_data[moving_average_data.index>= '2015-01-01']


plt.plot(stock_data_subset.index, stock_data_subset['Close'],color='tab:blue',alpha = 0.4)
plt.plot(moving_average_data_subset.index,moving_average_data_subset['Close'],color='tab:red')
plt.title("Time series analysis of MTN Group Limited Stocks VS Moving Average",fontsize = 17)

# Plot the residuals
plt.figure(figsize= (18,10))

residuals = stock_data - moving_average_data
plt.hist(residuals, bins=50)
plt.title("Residuals of MTN Group Limited Stocks and Moving Average",fontsize = 17)
plt.show()

percentile_90 = np.nanpercentile(abs(residuals['Close']),90)

residuals[abs(residuals['Close']) >= percentile_90]

# Ch7/5 Performing Smoothing - Exponential Smoothing.ipynb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.api import ExponentialSmoothing

stock_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/MTNOY.csv")
stock_data = stock_data[['Date','Close']]

quick_eda(stock_data, "7-analysis-time-series-in-python/MTNOY.csv")

stock_data['Date']= pd.to_datetime(stock_data['Date'], format = "%Y-%m-%d")

stock_data.set_index('Date',inplace = True)
stock_data.shape

# Perform Exponential Smoothing
exponentialmodel = ExponentialSmoothing(stock_data)
fit = exponentialmodel.fit(smoothing_level=0.7)

fitted_values = fit.fittedvalues

plt.figure(figsize= (18,10))

stock_data_subset = stock_data[stock_data.index>= '2015-01-01']
fitted_values_subset = fitted_values[fitted_values.index>= '2015-01-01']


plt.plot(stock_data_subset.index,
         stock_data_subset['Close'],
         label='Original Data',
         color='tab:blue',
         alpha = 0.4)

plt.plot(fitted_values_subset.index,
         fitted_values_subset.values,
         label='Exponential Smoothing',
         color='tab:red')

plt.title("Time series analysis of MTN Group Limited Stocks VS Exponential Smoothing Data",
          fontsize = 17)

# Plot the residuals
plt.figure(figsize= (18,10))

residuals = stock_data.squeeze() - fitted_values
plt.hist(residuals, bins=50)
plt.title("Residuals of MTN Group Limited Stocks and Exponential Smoothing",fontsize = 17)
plt.show()

# Identify residuals greater than 90th percentile and review
percentile_90 = np.nanpercentile(abs(residuals),90)

residuals[abs(residuals) >= percentile_90]

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller

air_traffic_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/SF_Air_Traffic_Passenger_Statistics_Transformed.csv")

quick_eda(air_traffic_data, "SF_Air_Traffic_Passenger_Statistics_Transformed")

# Transform date int to date
air_traffic_data['Date']= pd.to_datetime(air_traffic_data['Date'], format = "%Y%m")
air_traffic_data.dtypes

# Set date as index
air_traffic_data.set_index('Date',inplace = True)
air_traffic_data.shape

# Check Stationarity
adf_result = adfuller(air_traffic_data)
adf_result

print('ADF Test Statistic: %f' % adf_result[0])

print('p-value: %f' % adf_result[1])

print('Critical Values:')

print(adf_result[4])

if adf_result[0] < adf_result[4]["5%"]:
    print ("Reject Null Hypothesis - Time Series is Stationary")
else:
    print ("Failed to Reject Null Hypothesis - Time Series is Non-Stationary")

# Make the data stationary
air_traffic_data['Difference'] = air_traffic_data['Total Passenger Count'].diff(periods=1)

# Drop missing values
air_traffic_data = air_traffic_data.dropna()

# Plot stationary time series against original time series
plt.figure(figsize= (18,10))

plt.plot(air_traffic_data['Total Passenger Count'], label='Total Passenger Count')
plt.plot(air_traffic_data['Difference'], label='First-order difference', color='tab:red')
plt.title('Total Passenger Count VS Passenger Count with first-order difference', size=15)
plt.legend()

# Check Stationarity
adf_result = adfuller(air_traffic_data['Difference'], autolag='AIC')
adf_result

print('ADF Test Statistic: %f' % adf_result[0])

print('p-value: %f' % adf_result[1])

print('Critical Values:')

print(adf_result[4])

if adf_result[0] < adf_result[4]["5%"]:
    print ("Reject Null Hypothesis - Time Series is Stationary")
else:
    print ("Failed to Reject Null Hypothesis - Time Series is Non-Stationary")

from statsmodels.tsa.stattools import acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

air_traffic_data = pd.read_csv("/content/data/7-analysis-time-series-in-python/SF_Air_Traffic_Passenger_Statistics_Transformed.csv")

quick_eda(air_traffic_data, "SF_Air_Traffic_Passenger_Statistics_Transformed")

# Compute Autocorrelation
acf_values = acf(air_traffic_data[['Total Passenger Count']],nlags = 24)
for i in range(0,25):
    print("Lag " ,i, " " , np.round(acf_values[i],2))

# Plot Autocorrelation
fig= plot_acf(air_traffic_data['Total Passenger Count'],lags = 24)
fig.set_size_inches((10, 9))
plt.show()

# Compute Partial Autocorrelation
pacf_values = pacf(air_traffic_data['Total Passenger Count'],nlags=24,method="ols")
for i in range(0,25):
    print("Lag " ,i, " " , np.round(pacf_values[i],2))

# Plot Partial Autocorrelation
fig = plot_pacf(air_traffic_data['Total Passenger Count'],method = 'ols', lags=24)
fig.set_size_inches((10, 9))
plt.show()

